### ISSUE TITLE
Secure Password Handling

### ISSUE THREAD

**Issue by LuckySeb** [Luftbaum/WebUntisAPI-Java#2]
I have implemented a saver method that can be used when logging in with a password and thought maybe it will be useful some day ( password still needs to be set to zero in WebUntisConnection after login to be absolutly sure )

[HTTPSConnectionImpr.txt](https://github.com/Luftbaum/WebUntisAPI/files/1629339/HTTPSConnectionImpr.txt)

**Comment by Airdevelopments** [comment]
I am currently reworking the library, making it cleaner, adding some documentation and better samples as well.

Sorry I didn't see this earlier, this project has been laying around for some while now... anyway, will be looking into implementing it.

Thank you, I will close this issue when implemented!
